### ISSUE TITLE
Merchant record validation

### ISSUE THREAD

**Issue by andrewnisbet74** [andrewnisbet74/hawkeye#17]
Add the ability to validate merchant records as they are parsed from the upload files

Minimum acceptable fields
* Merchant DBA
* Legal name
* Address_1
* City 

If records do not have these values they should be rejected.  We will need a way to track rejections and notify users.  Options for this include create the records with a rejected status, and noting in the UI, or adding some sort of note filed to the file object and adding a list of the rejected merchants and why.  I think option 1 makes the most sense, but I am open to discussion.  We will want to have some way of communicating which records were rejected when we create the output file.

**Comment by DeathMetalCoder** [comment]
Fixed in: https://github.com/andrewnisbet74/hawkeye/pull/29
