### ISSUE TITLE
Clean up failed Urls

### ISSUE THREAD

**Issue by andrewnisbet74** [andrewnisbet74/hawkeye#20]
Determine a process that will allow us to delete url records that have failed matching after a period of time.   

- [ ]  Define a time period that makes sense(something like 30 days). 
- [ ]  Create a process that collects all of the url records that have aged past this time period, and have a status of failed matching,  and deletes them. records that are matched should not be deleted. 
- [ ] Add suitable unit tests to validate this works as expected

**Comment by DeathMetalCoder** [comment]
@andrewnisbet74 
We only try to match once right? So once a customer submits a file, we ingest it, try to match them, and then we are done. We would not try to match a failed record again unless we received the record again in the merchant file. Is this what you are envisioning?

**Comment by andrewnisbet74** [comment]
Yes, that is what I am thinking.  Saving the failed matches over time doesn't really help us since the web will change.
